package/leonp5/hybridcms/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

use Leonp5\Hybridcms\Http\Controllers\HomeController;
use Leonp5\Hybridcms\Http\Controllers\Auth\LoginController;
use Leonp5\Hybridcms\Http\Controllers\Admin\PagesController;
use Leonp5\Hybridcms\Http\Controllers\Admin\UsersController;
use Leonp5\Hybridcms\Http\Controllers\Admin\LanguagesController;
use Leonp5\Hybridcms\Http\Controllers\FrontendController\FrontendController;

// Frontend

$cmsPrefix = config('hybridcms.cms_prefix');
$cmsUrl = '/' . $cmsPrefix;


// Route::get('{locale}', [FrontendController::class, 'receiveMultiLangRequest'])->where('locale', '[a-zA-Z]{2}')
//     ->name('frontend.multilang.start')->middleware('addlocale');

// Route::any('{locale}/{url}', [FrontendController::class, 'receiveMultiLangRequest'])->where(['url' => "^((?!${cmsPrefix}).)*?", 'locale' => '[a-zA-Z]{2}'])
//     ->name('frontend.multilang')->middleware('addlocale');

/**
 * The regex in the where clause excludes ONLY the 'cms' prefix string. If the string is something like 'foocms' or 'cmsfoo' 
 * the the request will be passed to the notMatchingUrl method
 * 
 *  */
Route::any('{url}', [FrontendController::class, 'receiveRequest'])
    ->name('frontend')->middleware('addlocale')->where('url', "^((?!(?<!\w)${cmsPrefix}(?!\w)).)*?");


// Backend (Cms)

// prefix all possible routes with /cms
Route::group(
    [
        'prefix' => $cmsUrl,
        'middleware' => 'lastonline'
    ],
    function () {

        // Set language
        Route::get('/locale/{locale}', function ($locale) {
            Session::put('locale', $locale);
            return redirect()->back();
        })->name('localization.backend');

        Route::get('/', [HomeController::class, 'welcome'])->name('welcome');
        Route::get('/dashboard', [HomeController::class, 'dashboard'])->name('dashboard');

        Route::get('/login', [LoginController::class, 'show'])->name('login');
        Route::post('/login', [LoginController::class, 'login']);
        Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

        /*
        * IMPORTANT: The url is used in the url validation of page creation and update process
        * 
        * Add, edit, move & delete pages
        */

        Route::resource(
            'pages',
            PagesController::class,
            ['except' => ['show']]
        )->middleware('auth');

        /**
         * Add, edit, delete users & their roles
         */
        Route::resource(
            'users',
            UsersController::class,
            ['except' => ['show']]
        )->middleware('can:admin');

        Route::resource(
            'languages',
            LanguagesController::class,
            ['except' => ['destroy, create, show']]
        )->middleware('can:admin');
    }
);

package/leonp5/hybridcms/resources/views/backend/admin/languages/index.blade.php
@extends('hybridcms::backend.layout.app')

@section('title', __('hybridcms::pages.title.languages.index'))

@if(count($activeLanguages) > 0)
@section('styles')
<link href="{{ asset('backend/flags.css') }}" rel="stylesheet">
@endsection
@endif

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col">
            <h3 class="mb-3">{{__('hybridcms::admin.languages.settings')}}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
            @if(count($activeLanguages) > 0)
            <form class="card" id="hcms-language-checkboxes" action="{{route('languages.store')}}" method="POST">
                @csrf
                <h5 class="card-header">{{__('hybridcms::admin.languages.active.heading')}}
                    <span class="badge badge-pill badge-primary float-right"
                        id="hcms_active_lang_count">{{count($activeLanguages)}}</span>
                </h5>
                <div class="card-body">
                    <table class="table">
                        <thead class="table-light">
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">{{__('hybridcms::admin.languages.table.heading.language')}}</th>
                                <th scope="col">{{__('hybridcms::admin.languages.table.heading.main-language')}}</th>
                                <th scope="col">{{__('hybridcms::admin.languages.table.heading.disable')}}</th>
                                <th scope="col">{{__('hybridcms::admin.languages.table.heading.delete')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($activeLanguages as $language)
                            <tr class="{{$language->disabled ? "bg-light text-dark" : ""}}"
                                data-hcms-language-id="{{$language->id}}"
                                data-hcms-language-alpha_2="{{$language->alpha_2}}">
                                <input type="hidden" name="languages[{{$language->lang_id}}][alpha_2]"
                                    value="{{$language->alpha_2}}" />
                                <td>
                                    <span class="flag-icon flag-icon-{{$language->alpha_2}}"></span>
                                </td>
                                <td>
                                    <p id="lang_name_{{$language->alpha_2}}">{{$language->langName}}</p>
                                </td>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input"
                                            id="main_{{$language->lang_id}}"
                                            {{$language->main_language ? "checked" : "disabled"}}
                                            value="{{$language->main_language}}"
                                            name="languages[{{$language->lang_id}}][main_language]"
                                             data-hcms-main-language="">
                                        <label class="custom-control-label" for="main_{{$language->lang_id}}"></label>
                                    </div>
                                </td>
                                <td>
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input"
                                            id="disabled_{{$language->lang_id}}"
                                            {{$language->main_language ? "disabled" : ""}}
                                            {{$language->disabled ? "checked" : ""}} value="{{$language->disabled}}"
                                            name="languages[{{$language->lang_id}}][disabled]" data-hcms-lang-disabled="">
                                        <label class="custom-control-label"
                                            for="disabled_{{$language->lang_id}}"></label>
                                    </div>
                                </td>
                                <td>
                                    <x-hybridcms-svg svg="trash" fill="none"
                                        class="{{$language->main_language ? 'svg-delete hcms-pointer-forbidden' : 'svg-delete'}}"
                                        name="delete" />
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-end">
                        <button class="btn btn-success hcms-pointer-forbidden" type="submit" disabled
                            id="hmcs-update-languages">
                            {{__('hybridcms::admin.languages.table.button.update')}}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card">
                <h5 class="card-header">{{__('hybridcms::admin.languages.all.heading')}}
                    <span class="badge badge-pill badge-primary float-right"
                        id="hcms_all_lang_count">{{count($allLanguages)}}</span>
                </h5>
                <div class="card-body">
                    <div class="form-group row">
                        <div class="col">
                            <div class="input-group">
                                <input class="form-control" id="all_lang_search">
                                <span class="input-group-append">
                                    <button class="btn" type="button">
                                        <x-hybridcms-svg svg="magnifying-glass" viewBox="512 512" />
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex flex-wrap" id="hcms_all_languages">
                        @foreach($allLanguages as $language)
                        <div class="col-6 col-md-4 col-lg-3" name="hcms_lang_container">
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="lang_{{$language->id}}"
                                    {{isset($language->enabled) ? "checked" : ""}}
                                    data-hcms-language-id="{{$language->id}}" name="{{$language->name}}"
                                    value="{{$language->alpha_2}}">
                                <label class="custom-control-label"
                                    for="lang_{{$language->id}}">{{$language->name}}</label>
                                <span class="flag-icon flag-icon-{{$language->alpha_2}}"></span>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
    @else
    <h4 class="text-center">{{__('hybridcms::admin.languages.multilang.disabled')}}</h4>
    @endif
</div>
@endsection

package/leonp5/hybridcms/resources/views/backend/admin/users/create.blade.php
@extends('hybridcms::backend.layout.app')

@section('title', __('hybridcms::pages.title.users.add'))

@section('content')

<div class="container">
    <h3>{{__('hybridcms::admin.create.user')}}</h3>

    <form action="{{route('users.store')}}" method="POST">
       
        @include('hybridcms::backend.admin.users.partials.fields')
        
        <div class="form-group d-flex justify-content-between">
            <a href="{{ url()->previous() }}" class="btn btn-secondary">{{__('hybridcms::admin.create.user.abort')}}</a>
            <button type="submit" class="btn btn-primary">{{__('hybridcms::admin.create.user.submit')}}</button>
        </div>
    </form>

</div>

@endsection

package/leonp5/hybridcms/resources/views/backend/admin/users/edit.blade.php
@extends('hybridcms::backend.layout.app')

@section('title', __('hybridcms::pages.title.users.edit', ['username' => $user->username]))

@section('content')

<div class="container">
    <h3>{{__('hybridcms::admin.edit.user', ['username' => $user->username])}}</h3>

    <form action="{{route('users.update', ['user' => $user->uuid])}}" method="POST">
        @method('PUT')

        @include('hybridcms::backend.admin.users.partials.fields')
        
        <div class="form-group d-flex justify-content-between">
            <a href="{{ url()->previous() }}" class="btn btn-secondary">{{__('hybridcms::admin.edit.abort')}}</a>
            <button type="submit" class="btn btn-primary">{{__('hybridcms::admin.edit.submit')}}</button>
        </div>
    </form>

</div>

@endsection

package/leonp5/hybridcms/resources/views/backend/admin/users/index.blade.php
@extends('hybridcms::backend.layout.app')

@section('title', __('hybridcms::pages.title.users.index'))


@section('content')

<div class="container">
  <a class="btn btn-primary mb-3" href="{{route('users.create')}}">{{__('hybridcms::admin.add.user')}}</a>
  @if(count($allUsers) > 0)
  <table class="table">
    <thead>
      <tr>
        <th scope="col">{{__('hybridcms::admin.table.user.name')}}</th>
        <th scope="col">{{__('hybridcms::admin.table.user.role')}}</th>
        <th scope="col">{{__('hybridcms::admin.table.user.last-online')}}</th>
        <th scope="col">
          
        </th>
      </tr>
    </thead>
    <tbody>
      @foreach ($allUsers as $user)
      <tr>
        <td>
          <a href="{{route('users.edit', ['user' => $user->uuid])}}">
            {{$user->username}}</a>
        </td>
      <td>{{ $user->roles}}</td>
      {{-- <td class="td">{{ implode(", ", $user->roles()->get()->pluck("role")->toArray()) }}</td> --}}
      <td>{{$user->last_online_at}}</td>

        <td>
          <a type="button" data-toggle="modal" data-target="{{'#deleteConfirmModal' . $user->uuid}}">
            <x-hybridcms-svg svg="trash" fill="none" class="svg-delete"/></td>
          </a>
          <div class="modal fade" id="{{'deleteConfirmModal'. $user->uuid}}" tabindex="-1" aria-labelledby="deleteConfirmModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteConfirmModalLabel">{{__('hybridcms::admin.delete.modal.title')}}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                 <div class="row m-2"> 
                   {{__('hybridcms::admin.delete.user.modal.text', ['user' => $user->username])}} 
                </div> 
                 <div class="row m-2">
                   <div class="col">
                  <button type="button" class="btn btn-secondary m-2" data-dismiss="modal">{{__('hybridcms::admin.delete.abort')}}</button>
                </div>
                  <div class="col align-self-end">
                    <form method="POST" action="{{route('users.destroy', [$user->uuid])}}">
                      {{csrf_field()}}
                      <input type="hidden" name="_method" value="DELETE">
                      <button type="submit" class="btn btn-danger m-2">{{__('hybridcms::admin.delete.user.confirm')}}</button>
                    </form>
                  </div>
                </div>
                {{-- <div class="modal-footer">
                  
                </div> --}}
              </div>
            </div>
          </div>
      </tr>
      @endforeach
    </tbody>
  </table>
  @else
  <div class="d-flex justify-content-center">
    <h4 class='text-info'>{{__('hybridcms::admin.table.users.no-users')}}</h5>
  </div>
  @endif
</div>
@endsection

package/leonp5/hybridcms/resources/views/backend/components/svg.blade.php
<svg
    width="{{ $width }}"
    height="{{ $height }}"
    viewBox="0 0 {{ $viewBox }}"
    fill="{{ $fill }}"
    stroke="currentColor"
    stroke-width="{{ $strokeWidth }}"
    stroke-linecap="round"
    stroke-linejoin="round"
    id="{{ $id }}"
    {{ $attributes->merge(['class' => $class])}}
    {{-- class="w-8 h-8" --}}
    >
    @includeIf("hybridcms::backend.svgs.$svg")
</svg>

package/leonp5/hybridcms/resources/views/backend/layout/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>
        @if(View::hasSection('title'))
        @yield('title')
        @else
        hybridCms dev app
        @endif
    </title>

    <link href="{{ asset('backend/hcms.css') }}" rel="stylesheet">
    @yield('styles')
    
</head>

<body>
    @auth
    @include('hybridcms::backend.layout.partials.sidebar')  
    @endauth
    <div class="c-wrapper c-fixed-components">
        @include('hybridcms::backend.layout.partials.nav')
        <div class="c-body">
            <main class="c-main">
                @include('hybridcms::backend.layout.partials.alerts')
                @yield('content')
            </main>
        </div>
    </div>
    <script src="{{ asset('backend/hcms.js') }}" defer></script>
    <script src="{{ asset('backend/hcms-vendor.js')}}"></script>
</body>

</html>

package/leonp5/hybridcms/resources/views/backend/layout/partials/alerts.blade.php
@if(count($errors) > 0)
<div class="warning-modal" onclick="RemoveAlert()">
  @foreach($errors->all() as $error)
  {{$error}} <br>
  @endforeach
</div>
@endif

@if(session("success"))
<div class="alert-modal" onclick="RemoveAlert()">
  {{session("success")}}
</div>
@endif

@if(session("error"))
<div class="warning-modal" onclick="RemoveAlert()">
  {{session("error")}}
</div>
@endif

package/leonp5/hybridcms/resources/views/backend/layout/partials/nav.blade.php
<header class="c-header c-header-light c-header-fixed bg-light px-3">
    @auth
    <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar"
        data-class="c-sidebar-lg-show" responsive="true">
        <span class="c-header-toggler-icon"></span>
    </button>
    <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar"
        data-class="c-sidebar-show">
        <span class="c-header-toggler-icon"></span>
    </button>
    <!-- Left Side Of Navbar -->
    <ul class="c-header-nav d-md-down-none">
        <li class="c-header-nav-item px-3">
            <a class="c-header-nav-link" href="{{ route('dashboard') }}">Dashboard</a>
        </li>
    </ul>
    @endauth

    <!-- Right Side Of Navbar -->
    <ul class="c-header-nav ml-auto mr-4">
        @guest
        <li class="c-header-nav-item">
            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>
        @if (Route::has('register'))
        <li class="c-header-nav-item">
            <a class="c-header-nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
        </li>
        @endif
        @else
        <li class="c-header-nav-item dropdown">
            <a class="c-header-nav-link" data-toggle="dropdown" href="" role="button" aria-haspopup="true" aria-expanded="true">
                <div class="c-avatar">
                    <x-hybridcms-svg svg="user-circle" viewBox="496 512"></x-hybridcms-svg>
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
                <div class="dropdown-header bg-light py-2">
                    <strong>{{__('hybridcms::navigation.languages')}}</strong>
                </div>
                <a class="dropdown-item" href="{{ route('localization.backend', ['locale' => 'gb']) }}">
                    <x-hybridcms-svg svg="flag_gb" class="c-icon mr-2" width="301" height="181" viewBox="301 181" />
                    GB</a>
                <a class="dropdown-item" href="{{ route('localization.backend', ['locale' => 'de']) }}">
                    <x-hybridcms-svg svg="flag_de" class="c-icon mr-2" width="301" height="181" viewBox="301 181" />
                    DE</a>
                <div class="dropdown-header bg-light py-2">
                    <strong>  {{ Auth::user()->username }}</strong>
                </div>
                <a class="dropdown-item" href="#">
                    <x-hybridcms-svg svg="account" class="c-icon mr-2" viewBox="512 512" />
                    {{__('hybridcms::navigation.user.dropdown.account')}}</a>
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                document.getElementById('logout-form').submit();">
                    <x-hybridcms-svg svg="logout" class="c-icon mr-2" viewBox="512 512" />
                    {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
            </div>
        </li>
        @endguest
    </ul>
</header>

package/leonp5/hybridcms/resources/views/backend/layout/partials/sidebar.blade.php
{{-- <div class="c-sidebar c-sidebar-dark c-sidebar-show"> --}}
<div id="sidebar" class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show">
  <div class="c-sidebar-brand d-md-down-none">
    hybridCMS
  </div>
  <ul class="c-sidebar-nav">
    <li class="c-sidebar-nav-title">
      {{ __('hybridcms::navigation.pages')}}</li>
    <li class="c-sidebar-nav-item">
      <a class="c-sidebar-nav-link" href="{{ route('pages.index') }}">
        <x-hybridcms-svg svg="library" class="c-sidebar-nav-icon" viewBox="512 512" />
        {{__('hybridcms::navigation.pages.overview')}}
      </a>
    </li>
    @canany(['admin', 'editor'])
    <li class="c-sidebar-nav-item">
      <a class="c-sidebar-nav-link" href="{{ route('pages.create') }}">
        <x-hybridcms-svg svg="library-add" class="c-sidebar-nav-icon" viewBox="512 512" />
        {{__('hybridcms::navigation.pages.create')}}
      </a>
    </li>
    @endcanany
    @can('admin')
    <li class="c-sidebar-nav-title">
      {{ __('hybridcms::navigation.user.management')}}
    </li>
    <li class="c-sidebar-nav-item">
      <a class="c-sidebar-nav-link" href="{{ route('users.index') }}">
        <x-hybridcms-svg svg="group" class="c-sidebar-nav-icon" viewBox="512 512" />
        {{__('hybridcms::navigation.users.overview')}}
      </a>
    </li>
    <li class="c-sidebar-nav-item">
      <a class="c-sidebar-nav-link" href="{{ route('users.create') }}">
        <x-hybridcms-svg svg="user-add" class="c-sidebar-nav-icon" viewBox="512 512" />
        {{__('hybridcms::navigation.users.create')}}
      </a>
    </li>

    <li class="c-sidebar-nav-item c-sidebar-nav-dropdown mt-auto">
      <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="">
        <x-hybridcms-svg svg="settings" class="c-sidebar-nav-icon" viewBox="512 512" />
        {{__('hybridcms::navigation.user.dropdown.settings')}}</a>
        <ul class="c-sidebar-nav-dropdown-items">
          <li class="c-sidebar-nav-item">
            <a class="c-sidebar-nav-link" href="{{route('languages.index')}}">
              {{__('hybridcms::navigation.languages.settings')}}
            </a>
          </li>
        </ul>
    </li>
    @endcan
  </ul>
  <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent"
    data-class="c-sidebar-minimized"></button>
</div>

package/leonp5/hybridcms/resources/views/backend/svgs/flag_de.blade.php
<g fill="none">
    <path fill="#000" d="M.5.5h300v180H.5z"/>
    <path fill="#D00" d="M.5 60.5h300v120H.5z"/>
    <path fill="#FFCE00" d="M.5 120.5h300v60H.5z"/>
  </g>

package/leonp5/hybridcms/resources/views/backend/user/pages/create.blade.php
@extends('hybridcms::backend.layout.app')

@section('title', __('hybridcms::pages.title.page.create'))

@section('content')

<div class="container">
    <h3>{{__('hybridcms::admin.create.page')}}</h3>

    <form action="{{route('pages.store')}}" method="POST">

        @include('hybridcms::backend.user.pages.partials.fields')
        <div class="form-group d-flex justify-content-between">
            <a href="{{ url()->previous() }}" class="btn btn-secondary">{{__('hybridcms::admin.edit.abort')}}</a>
            <button type="submit" class="btn btn-primary">{{__('hybridcms::admin.create.submit')}}</button>
        </div>
    </form>

</div>

@endsection

package/leonp5/hybridcms/resources/views/backend/user/pages/edit.blade.php
@extends('hybridcms::backend.layout.app')

@section('title', __('hybridcms::pages.title.page.edit'))

@section('content')

<div class="container">
    <h3>{{__('hybridcms::admin.edit.page')}}</h3>

    <form action="{{route('pages.update', ['page' => $page->id])}}" method="POST">
        @method('PUT')

        @include('hybridcms::backend.user.pages.partials.fields')
        
        <div class="form-group d-flex justify-content-between">
            <a href="{{ url()->previous() }}" class="btn btn-secondary">{{__('hybridcms::admin.edit.abort')}}</a>
            <button type="submit" class="btn btn-primary">{{__('hybridcms::admin.edit.submit')}}</button>
        </div>
    </form>

</div>

@endsection

package/leonp5/hybridcms/resources/views/backend/user/pages/index.blade.php
@extends('hybridcms::backend.layout.app')

@section('title', __('hybridcms::pages.title.pages.index'))

@section('content')

<div class="container">
  @canany(['admin', 'editor'])
  <a class="btn btn-primary mb-3" href="{{route('pages.create')}}">{{__('hybridcms::admin.create.page')}}</a>
  @endcanany
  @if(count($allPages) > 0)
  <table class="table table-responsive-sm">
    <thead>
      <tr>
        <th scope="col">{{__('hybridcms::admin.page.title')}}</th>
        <th scope="col">URL</th>
        <th scope="col">Status</th>
        <th scope="col">{{__('hybridcms::admin.page.available.lang')}}</th>
        @canany(['admin', 'editor'])
        <th scope="col"></th>
        @endcanany
        </th>
      </tr>
    </thead>
    <tbody>
      @foreach ($allPages as $page)
      <tr>

        <td>
          <a href="{{route('pages.edit', ['page' => $page->id])}}">
            {{$page->title !== null ? $page->title : __('hybridcms::admin.page.title.missing')}}</a>
        </td>

        <td>{{ $page->url !== null ? $page->url : __('hybridcms::admin.page.url.missing')}}</td>

        @if($page->page_status_id === 2)
        <td>
          <span class="badge badge-warning">
            {{__('hybridcms::admin.page.status.draft')}}
          </span></td>
        @elseif ($page->page_status_id === 3)
        <td>
          <span class="badge badge-secondary">
            {{__('hybridcms::admin.page.status.inactive')}}
          </span></td>
        @elseif($page->page_status_id === 1)
        <td>
          <span class="badge badge-success">{{__('hybridcms::admin.page.status.published')}}
          </span></td>
        @endif

        <td>{{$page->available_lang}}</td>

        @canany(['admin', 'editor'])
        <td>
          <a type="button" data-toggle="modal" data-target="{{'#deleteConfirmModal' . $page->id}}">
            <x-hybridcms-svg svg="trash" fill="none" class="svg-delete"/></td>
          </a>
          <div class="modal fade" id="{{'deleteConfirmModal'. $page->id}}" tabindex="-1" aria-labelledby="deleteConfirmModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteConfirmModalLabel">{{__('hybridcms::admin.delete.modal.title')}}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                 <div class="row m-2"> {{__('hybridcms::admin.delete.modal.text')}}</div> 
                 <div class="row m-2">
                   <div class="col">
                  <button type="button" class="btn btn-secondary m-2" data-dismiss="modal">{{__('hybridcms::admin.delete.abort')}}</button>
                </div>
                  <div class="col align-self-end">
                    <form method="POST" action="{{route('pages.destroy', [$page->id])}}">
                      {{csrf_field()}}
                      <input type="hidden" name="_method" value="DELETE">
                      <button type="submit" class="btn btn-danger m-2">{{__('hybridcms::admin.delete.page.confirm')}}</button>
                    </form>
                  </div>
                </div>
                {{-- <div class="modal-footer">
                  
                </div> --}}
              </div>
            </div>
          </div>
        </td>
        @endcanany
      </tr>
      @endforeach
    </tbody>
  </table>
  
  {{$allPages->links()}}
  @else
  <div class="d-flex justify-content-center">

    <h4 class='text-info'>{{__('hybridcms::admin.page.no-pages')}}</h5>
  </div>
  @endif
</div>
@endsection